apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

nodeGroups:
  - name: hello-world-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    volumeSize: 20
