apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
      - name: hello-world-api
        image: 145023105377.dkr.ecr.us-east-1.amazonaws.com/hello-world-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
