apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rajwinder3/kubernete-argocd.git
    targetRevision: main
    path: hello-world-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
